name: Bug 报告
description: 提交一个可复现的 Bug 帮助我们改进项目
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 简要描述你遇到的问题，以及期望的行为
      placeholder: |
        当我调用 ListCompressor 时，期望得到 ...，但实际结果是 ...
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: 复现步骤
      description: 尽量提供最小可复现代码、输入示例和配置
      placeholder: |
        1. 使用输入 [...]
        2. 调用 API [...]
        3. 观察输出 [...]
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: 运行环境
      description: 包括 .NET 版本、操作系统、NuGet 包版本等
      placeholder: |
        - OS:
        - .NET SDK:
        - LbxyCommonLib.ListCompression 版本:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 日志/堆栈信息（如有）
      description: 请粘贴相关异常、堆栈或日志信息
      render: shell
    validations:
      required: false

